"""M3 configuration and serving metadata

Revision ID: a701c3d717e0
Revises:
Create Date: 2026-10-07 15:32:59.535878
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a701c3d717e0"
down_revision: str | None = None
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "model_releases",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.String(length=16), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("supports_temperature", sa.Boolean(), nullable=False),
        sa.Column("default_temperature", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("provider IN ('fake','openai','groq')"),
        sa.CheckConstraint(
            "default_temperature IS NULL OR "
            "(supports_temperature AND default_temperature BETWEEN 0 AND 2)"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "routing_configs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("stable_release_id", sa.Uuid(), nullable=False),
        sa.Column("candidate_release_id", sa.Uuid(), nullable=True),
        sa.Column("canary_weight", sa.Integer(), nullable=False),
        sa.Column("shadow_sample_rate", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("mode = 'canary' OR canary_weight = 0"),
        sa.CheckConstraint("mode = 'shadow' OR shadow_sample_rate = 0"),
        sa.CheckConstraint(
            "mode = 'stable' OR (candidate_release_id IS NOT NULL "
            "AND candidate_release_id <> stable_release_id)"
        ),
        sa.CheckConstraint("mode IN ('stable','canary','shadow')"),
        sa.CheckConstraint(
            "canary_weight BETWEEN 0 AND 100 AND shadow_sample_rate BETWEEN 0 AND 100"
        ),
        sa.ForeignKeyConstraint(
            ["candidate_release_id"],
            ["model_releases.id"],
        ),
        sa.ForeignKeyConstraint(
            ["stable_release_id"],
            ["model_releases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("version"),
    )
    op.create_table(
        "activation_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("previous_config_id", sa.Uuid(), nullable=True),
        sa.Column("config_id", sa.Uuid(), nullable=False),
        sa.Column("actor", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["config_id"],
            ["routing_configs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["previous_config_id"],
            ["routing_configs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "active_config",
        sa.Column("singleton", sa.Integer(), nullable=False),
        sa.Column("config_id", sa.Uuid(), nullable=True),
        sa.CheckConstraint("singleton = 1"),
        sa.ForeignKeyConstraint(
            ["config_id"],
            ["routing_configs.id"],
        ),
        sa.PrimaryKeyConstraint("singleton"),
    )
    op.create_table(
        "requests",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("config_id", sa.Uuid(), nullable=False),
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("serving_role", sa.String(length=16), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("routing_key_digest", sa.String(length=64), nullable=False),
        sa.Column("digest_version", sa.String(length=32), nullable=False),
        sa.Column("canary_bucket", sa.Integer(), nullable=False),
        sa.Column("shadow_bucket", sa.Integer(), nullable=False),
        sa.Column("shadow_selection", sa.String(length=40), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("serving_role IN ('stable','candidate')"),
        sa.CheckConstraint(
            "shadow_selection IN ('not_applicable','not_selected','selected_execution_deferred')"
        ),
        sa.CheckConstraint("canary_bucket BETWEEN 0 AND 9999 AND shadow_bucket BETWEEN 0 AND 9999"),
        sa.ForeignKeyConstraint(
            ["config_id"],
            ["routing_configs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["model_releases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_requests_config_id"), "requests", ["config_id"], unique=False)
    op.create_index(op.f("ix_requests_received_at"), "requests", ["received_at"], unique=False)
    op.create_table(
        "invocations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("serving_role", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("max_output_tokens", sa.Integer(), nullable=False),
        sa.Column("temperature", sa.Float(), nullable=True),
        sa.Column("latency_ms", sa.Float(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("total_tokens", sa.Integer(), nullable=True),
        sa.Column("finish_reason", sa.String(length=24), nullable=True),
        sa.Column("error_code", sa.String(length=40), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("serving_role IN ('stable','candidate')"),
        sa.CheckConstraint("status IN ('success','failed','cancelled')"),
        sa.CheckConstraint("input_tokens IS NULL OR input_tokens >= 0"),
        sa.CheckConstraint("max_output_tokens > 0 AND latency_ms >= 0"),
        sa.CheckConstraint("output_tokens IS NULL OR output_tokens >= 0"),
        sa.CheckConstraint("total_tokens IS NULL OR total_tokens >= 0"),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["model_releases.id"],
        ),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["requests.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("request_id", "release_id", "serving_role"),
    )
    op.create_index(op.f("ix_invocations_release_id"), "invocations", ["release_id"], unique=False)
    op.create_index(op.f("ix_invocations_status"), "invocations", ["status"], unique=False)
    op.execute("INSERT INTO active_config (singleton, config_id) VALUES (1, NULL)")
    op.execute("""
        CREATE FUNCTION prevent_history_mutation() RETURNS trigger AS $$
        BEGIN RAISE EXCEPTION 'Immutable history cannot be changed'; END;
        $$ LANGUAGE plpgsql
    """)
    for table in ("model_releases", "routing_configs", "activation_events"):
        op.execute(
            f"CREATE TRIGGER immutable_history BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION prevent_history_mutation()"
        )
    op.execute(
        "CREATE TRIGGER preserve_pointer BEFORE DELETE ON active_config "
        "FOR EACH ROW EXECUTE FUNCTION prevent_history_mutation()"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_invocations_status"), table_name="invocations")
    op.drop_index(op.f("ix_invocations_release_id"), table_name="invocations")
    op.drop_table("invocations")
    op.drop_index(op.f("ix_requests_received_at"), table_name="requests")
    op.drop_index(op.f("ix_requests_config_id"), table_name="requests")
    op.drop_table("requests")
    op.drop_table("active_config")
    op.drop_table("activation_events")
    op.drop_table("routing_configs")
    op.drop_table("model_releases")
    op.execute("DROP FUNCTION prevent_history_mutation()")
    # ### end Alembic commands ###
